name: Build and Release

on:
  workflow_dispatch:  # 手动触发
    inputs:
      tag_name:
        description: 'The tag name for the release'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # 你可以根据需要更改 .NET 版本

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./output

    - name: Archive production artifacts
      run: tar -czf release.tar.gz -C output .

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifact
        path: release.tar.gz

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download release artifact
      uses: actions/download-artifact@v4
      with:
        name: release-artifact
        path: ./release

    - name: Set default tag name
      id: set_tag_name
      run: |
        if [ -z "${{ github.event.inputs.tag_name }}" ]; then
          TAG_NAME=$(date +'%Y%m%d')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        else
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
        fi

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Release notes for ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/release.tar.gz
        asset_name: release.tar.gz
        asset_content_type: application/gzip
